const sampleListings = [
    { "body": "Post number 1 — enjoy the moment ✨", "photo": "https://picsum.photos/seed/post1/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 2 — keep pushing forward 💪", "photo": "https://picsum.photos/seed/post2/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 3 — happiness begins with gratitude 🌸", "photo": "https://picsum.photos/seed/post3/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 4 — stay motivated and focused 🌟", "photo": "https://picsum.photos/seed/post4/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 5 — believe in yourself 💯", "photo": "https://picsum.photos/seed/post5/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 6 — new day, new opportunities 🌞", "photo": "https://picsum.photos/seed/post6/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 7 — never stop learning 📚", "photo": "https://picsum.photos/seed/post7/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 8 — travel makes you rich ✈️", "photo": "https://picsum.photos/seed/post8/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 9 — enjoy the little things 🌼", "photo": "https://picsum.photos/seed/post9/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 10 — surround yourself with positivity 😇", "photo": "https://picsum.photos/seed/post10/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 11 — happiness looks good on you 😊", "photo": "https://picsum.photos/seed/post11/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 12 — keep shining ✨", "photo": "https://picsum.photos/seed/post12/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 13 — stay humble and kind 🤍", "photo": "https://picsum.photos/seed/post13/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 14 — progress over perfection 🔥", "photo": "https://picsum.photos/seed/post14/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 15 — consistency wins 💥", "photo": "https://picsum.photos/seed/post15/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 16 — don't quit, you're almost there 🏁", "photo": "https://picsum.photos/seed/post16/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 17 — dream big 🌙", "photo": "https://picsum.photos/seed/post17/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 18 — stay strong, stay unstoppable ⚡", "photo": "https://picsum.photos/seed/post18/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 19 — focus on the good 🌻", "photo": "https://picsum.photos/seed/post19/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 20 — breathe, relax, repeat 🌬️", "photo": "https://picsum.photos/seed/post20/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 21 — light up the world 💡", "photo": "https://picsum.photos/seed/post21/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 22 — joy is contagious 😄", "photo": "https://picsum.photos/seed/post22/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 23 — positivity always wins 🌈", "photo": "https://picsum.photos/seed/post23/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 24 — embrace the journey 🚶‍♂️", "photo": "https://picsum.photos/seed/post24/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 25 — create your own sunshine ☀️", "photo": "https://picsum.photos/seed/post25/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 26 — mindset is everything 🧠", "photo": "https://picsum.photos/seed/post26/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 27 — life is a beautiful adventure 🌍", "photo": "https://picsum.photos/seed/post27/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 28 — good things take time ⏳", "photo": "https://picsum.photos/seed/post28/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 29 — keep faith alive 🙏", "photo": "https://picsum.photos/seed/post29/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 30 — choose happiness everyday 🌟", "photo": "https://picsum.photos/seed/post30/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 31 — enjoy every step of your journey 🚶‍♀️", "photo": "https://picsum.photos/seed/post31/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 32 — celebrate small wins 🎉", "photo": "https://picsum.photos/seed/post32/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 33 — life begins outside your comfort zone 🚀", "photo": "https://picsum.photos/seed/post33/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 34 — be your own inspiration 💫", "photo": "https://picsum.photos/seed/post34/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 35 — laugh more, worry less 😄", "photo": "https://picsum.photos/seed/post35/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 36 — life is short, live fully ❤️", "photo": "https://picsum.photos/seed/post36/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 37 — be kind to your mind 🧘", "photo": "https://picsum.photos/seed/post37/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 38 — start where you are, use what you have 🔧", "photo": "https://picsum.photos/seed/post38/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 39 — focus on what matters most 🎯", "photo": "https://picsum.photos/seed/post39/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 40 — stay brave, stay bold 🦁", "photo": "https://picsum.photos/seed/post40/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 41 — live simply, dream big 🌌", "photo": "https://picsum.photos/seed/post41/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 42 — work hard in silence, let success speak 🔊", "photo": "https://picsum.photos/seed/post42/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 43 — don't look back, you're not going that way 🔄", "photo": "https://picsum.photos/seed/post43/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 44 — chase goals, not people 💼", "photo": "https://picsum.photos/seed/post44/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 45 — when in doubt, just take the next step 🚶", "photo": "https://picsum.photos/seed/post45/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 46 — bloom with grace 🌷", "photo": "https://picsum.photos/seed/post46/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 47 — life rewards courage 🏆", "photo": "https://picsum.photos/seed/post47/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 48 — good energy is contagious ⚡", "photo": "https://picsum.photos/seed/post48/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 49 — stay curious, keep exploring 🔍", "photo": "https://picsum.photos/seed/post49/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 50 — your vibe attracts your tribe ✨", "photo": "https://picsum.photos/seed/post50/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 51 — trust the timing of your life ⏰", "photo": "https://picsum.photos/seed/post51/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 52 — stay in your magic 🪄", "photo": "https://picsum.photos/seed/post52/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 53 — live with passion and purpose 🔥", "photo": "https://picsum.photos/seed/post53/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 54 — every step counts 👣", "photo": "https://picsum.photos/seed/post54/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 55 — happiness starts within 💗", "photo": "https://picsum.photos/seed/post55/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 56 — go wherever you feel most alive 🌄", "photo": "https://picsum.photos/seed/post56/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 57 — one day at a time ⏳", "photo": "https://picsum.photos/seed/post57/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 58 — stay hungry for growth 🌱", "photo": "https://picsum.photos/seed/post58/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 59 — choose love, always ❤️", "photo": "https://picsum.photos/seed/post59/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 60 — take risks, live fully 🎢", "photo": "https://picsum.photos/seed/post60/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 61 — protect your peace 🕊️", "photo": "https://picsum.photos/seed/post61/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 62 — find joy in simple moments 🍃", "photo": "https://picsum.photos/seed/post62/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 63 — become the best version of you 🚀", "photo": "https://picsum.photos/seed/post63/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 64 — don't stop until you're proud 🏆", "photo": "https://picsum.photos/seed/post64/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 65 — new beginnings are beautiful 🌅", "photo": "https://picsum.photos/seed/post65/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 66 — stay true to yourself 💖", "photo": "https://picsum.photos/seed/post66/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 67 — some days you just shine brighter 🌞", "photo": "https://picsum.photos/seed/post67/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 68 — life is meant to be experienced 🌍", "photo": "https://picsum.photos/seed/post68/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 69 — be fearless in the pursuit of joy 🦋", "photo": "https://picsum.photos/seed/post69/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 70 — choose peace over pressure 🌤️", "photo": "https://picsum.photos/seed/post70/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 71 — smile loudly without apology 😁", "photo": "https://picsum.photos/seed/post71/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 72 — time heals and teaches ⏱️", "photo": "https://picsum.photos/seed/post72/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 73 — you glow differently when you're happy ✨", "photo": "https://picsum.photos/seed/post73/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 74 — become unstoppable 🔥", "photo": "https://picsum.photos/seed/post74/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 75 — blessings are everywhere 🙌", "photo": "https://picsum.photos/seed/post75/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 76 — life feels lighter when you let go 🎈", "photo": "https://picsum.photos/seed/post76/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 77 — don't shrink to make others comfortable 🌙", "photo": "https://picsum.photos/seed/post77/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 78 — be grateful for today 🌾", "photo": "https://picsum.photos/seed/post78/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 79 — your dreams are valid 💭", "photo": "https://picsum.photos/seed/post79/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 80 — your only limit is your mind 🧠", "photo": "https://picsum.photos/seed/post80/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 81 — don't fear failure, fear regret ⚠️", "photo": "https://picsum.photos/seed/post81/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 82 — the best is yet to come 🌈", "photo": "https://picsum.photos/seed/post82/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 83 — be kind to others and yourself 💝", "photo": "https://picsum.photos/seed/post83/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 84 — you matter more than you think 💫", "photo": "https://picsum.photos/seed/post84/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 85 — trust the process 🔁", "photo": "https://picsum.photos/seed/post85/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 86 — life is happening now 🕰️", "photo": "https://picsum.photos/seed/post86/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 87 — never stop believing in magic 🪄", "photo": "https://picsum.photos/seed/post87/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 88 — storms make trees take deeper roots 🌳", "photo": "https://picsum.photos/seed/post88/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 89 — today is a fresh start 🌤️", "photo": "https://picsum.photos/seed/post89/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 90 — love yourself first 💟", "photo": "https://picsum.photos/seed/post90/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 91 — you are enough 💛", "photo": "https://picsum.photos/seed/post91/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 92 — one life, live it well 🌍", "photo": "https://picsum.photos/seed/post92/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 93 — breathe deeply, live fully 🌬️", "photo": "https://picsum.photos/seed/post93/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 94 — happiness is a choice 💖", "photo": "https://picsum.photos/seed/post94/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 95 — you can do hard things 💪", "photo": "https://picsum.photos/seed/post95/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 96 — trust your journey 🛣️", "photo": "https://picsum.photos/seed/post96/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" },
    { "body": "Post number 97 — keep showing up 🧡", "photo": "https://picsum.photos/seed/post97/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_4" },
    { "body": "Post number 98 — learn, unlearn, relearn 🔄", "photo": "https://picsum.photos/seed/post98/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_1" },
    { "body": "Post number 99 — stay wild, moon child 🌙", "photo": "https://picsum.photos/seed/post99/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_2" },
    { "body": "Post number 100 — good things are coming ✨", "photo": "https://picsum.photos/seed/post100/600/400", "likes": [], "comments": [], "postedBy": "USER_ID_3" }
]

module.exports = { data: sampleListings };